# =============================================
# SonarQube - Notes Vuln (Lab sécurité)
# =============================================

# Identification
sonar.projectKey=notes-vuln
sonar.projectName=Notes Vuln
sonar.projectVersion=1.0

# Description
sonar.projectDescription=Application Flask volontairement vulnérable pour démonstration DevSecOps

# Analyse
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/.venv/**,\
**/venv/**,\
**/__pycache__/**,\
**/*.pyc,\
**/*.db,\
**/instance/**,\
**/tests/**,\
**/test_*.py,\
**/*_test.py,\
**/.git/**,\
**/.idea/**,\
**/.vscode/**,\
**/node_modules/**,\
**/dist/**,\
**/build/**

# Work dir
sonar.working.directory=.sonarwork